<!Doctype html>
<html>
    <head>
        <title><?php echo $this->data["title"] ?></title>
        <link rel="stylesheet" href="css/styles.css" />
        <script src="https://code.jquery.com/jquery-1.11.3.js"></script>
    </head>
    <body>
        <?php 
    include "_nav.phtml";
    $this->renderBody(); ?>
        <footer>
            <hr />
            <div class="footer">&copy; Rich Hildred <script>document.write(new Date().getFullYear())</script><a href="privacy" class="pull-right">Privacy policy</a></div></footer>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    </body>
</html>