<?php 
$this->data["title"]="winona cat sitting: contact";
$this->layout("_layout.phtml");
?>
<h1>Contact</h1>
<div class="row">
    <div class="col-md-8">
        <script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=false"></script>
        <div style="overflow:hidden;height:500px;width:100%;">
            <div id="gmap_canvas" style="height:500px;width:100%;"></div>
            <style>
                #gmap_canvas img {
                    max-width: none!important;
                    background: none!important
                }
            </style><a class="google-map-code" href="http://www.trivoo.net/gutscheine/schwab/" id="get-map-data">www.trivoo.net</a>
        </div>
        <script type="text/javascript">
            var nLat = 43.218402,nLong = -79.633945;
            function init_map() {
                var myOptions = {
                    scrollwheel: false,
                    zoom: 12,
                    center: new google.maps.LatLng(nLat, nLong),
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                };
                map = new google.maps.Map(document.getElementById("gmap_canvas"), myOptions);
                marker = new google.maps.Marker({
                    map: map,
                    position: new google.maps.LatLng(nLat, nLong)
                });
                infowindow = new google.maps.InfoWindow({
                    content: "<b>plan-b</b><br/>Serving the Winona<br/>and Grimsby area"
                });
                google.maps.event.addListener(marker, "click", function () {
                    infowindow.open(map, marker);
                });
                infowindow.open(map, marker);
            }
            google.maps.event.addDomListener(window, 'load', init_map);
        </script>
    </div>
    <div class="col-md-4">
        <?php
        \RHildred\Editable\Markdown::render( __DIR__ . "/contact.md");
        ?>
    </div>
</div>