<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>
<script>
    angular.module("myApp", []).controller("myCtrl", function ($scope, $http){
        $scope.addProduct = function(){
            alert("addingProduct ... " + $scope.newProduct.name);
        }
    });
</script>
<form ng-app="myApp" ng-controller="myCtrl">
    <input placeholder="name" ng-model="newProduct.name" /> <input placeholder="description" ng-model="newProduct.description" /> <button type="submit" ng-click="addProduct()">Add Product</button>
</form>